### ISSUE TITLE
How to change the scan distance 

### ISSUE THREAD

**Issue by PauloSilva98** [ros-perception/slam_karto#34]
Hi there, 

I am using an Rplidar laser with an 25m scan range. I can't seem to find a parameter to change the maximum scan distance. Am I missing something or the scan range limit is hard coded?

**Comment by mikeferguson** [comment]
There is not a parameter for this - slam_karto reads this directly from your sensor_msgs/LaserScan message. It looks like this could be added - https://github.com/ros-perception/slam_karto/blob/melodic-devel/src/slam_karto.cpp#L412 - pull requests are welcome.

**Comment by PauloSilva98** [comment]
I see. However, what is happening is the following: 

![Screenshot from 2021-03-17 09-19-52](https://user-images.githubusercontent.com/47529465/111444268-1829a980-8702-11eb-87b6-6e387ad2e5fd.png)

The map seems to be updating up to a certain range, almost like it's not using the max range of scanner (seems to be about half). Could it be failing to read the max_range of my scan topic or could there be some other parameter causing this?

**Comment by stwirth** [comment]
As far as I understand, there is min range, max range and range threshold. Min range and max range are set from the laser messages but range threshold is independent of that and not initialized. Inside Karto, the range threshold is initialized to 12.0 here:
https://github.com/ros-perception/open_karto/blob/6991694d76468f34a5e26aa4a411ba94b1f5837b/include/open_karto/Karto.h#L4150

**Comment by PauloSilva98** [comment]
Yep, that seems to explain it. Ty.

**Comment by Seba-san** [comment]
Maybe you can set a _filter scan_ in the same launch file of karto slam. It worked for me. 
Link to laser scan filter:http://wiki.ros.org/laser_filters#LaserScanRangeFilter

In my case, the laser has 20m range and I want to limit to 9m. This is my "scan_filter.yaml":
```yaml
scan_filter_chain:
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.5
    upper_threshold: 9
    lower_replacement_value: -.inf
    upper_replacement_value: .inf
```
I hope that this was helpful for other with the same problem.
